/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dk_dtu_main_NativeWrapper */

#ifndef _Included_dk_dtu_main_NativeWrapper
#define _Included_dk_dtu_main_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dk_dtu_main_NativeWrapper
 * Method:    runAlgorithmNative
 * Signature: ([[III)[I
 */
JNIEXPORT jintArray JNICALL Java_dk_dtu_main_NativeWrapper_runAlgorithmNative
  (JNIEnv *, jobject, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
